export const LOGIN_USER_DATA = "LOGIN_USER_DATA";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const GET_ALL_SERVER = "GET_ALL_SERVER";
export const GET_ALL_TRACKS = "GET_ALL_TRACKS";
export const RUN_SERVER_CMD = "RUN_SERVER_CMD";
export const CHANGE_TRACK = "CHANGE_TRACK";